name: GCD Script Test
on: [push]

jobs:
  test-gcd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up script permissions
        run: chmod +x gcd.sh test_gcd.sh
      - name: Run tests
        run: ./test_gcd.sh

